### ISSUE TITLE
【依頼】ChatSpace挙動確認」

### ISSUE THREAD

**Issue by shokuro705** [shokuro705/ChatSpace#12]
# IPアドレス
18.178.167.27

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・画面を拡大／縮小させた際にSendボタンの位置がずれている
[![Screenshot from Gyazo](https://gyazo.com/77322c6c080a77972a75983dfe454ecc/raw)](https://gyazo.com/77322c6c080a77972a75983dfe454ecc)

修正完了次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shokuro705** [comment]
修正しました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by shokuro705** [comment]
ありがとうございました！！
